### ISSUE TITLE
The link to the dataset is expired

### ISSUE THREAD

**Issue by rkakamilan** [HankerWu/TamGent#2]
Failed to access it. Could you check the [link](https://github.com/HankerWu/TamGent/tree/main/dataset) ?

**Comment by HankerWu** [comment]
Updated. You can access the link now.

**Comment by rkakamilan** [comment]
Many thanks! I can access it!

**Comment by LucyLu-LX** [comment]
@rkakamilan sorry to bother you. I am trying to reimplement this repo. The link to the dataset is expired now and the author doesn't reply. Can you please share the dataset please? Many thanks.

**Comment by vaish-navii** [comment]
+1 for the link to dataset and pre-trained model
